[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ffmpeg==1.4",
    "flask>=3.1.1",
    "werkzeug>=3.1.3",
    "yt-dlp==2024.12.6",
]
